import AppKit
import SwiftUI

struct ClipItem: Identifiable, Equatable {
    let id = UUID()
    var text: String
    var date: Date
}

/// Копирования из одного приложения собраны в одну группу.
struct ClipGroup: Identifiable, Equatable {
    var id: String { bundleID }
    var bundleID: String
    var appName: String
    var items: [ClipItem]

    var latest: Date { items.first?.date ?? .distantPast }
}

/// История буфера обмена. Хранится только в памяти; пароли и прочее,
/// что менеджеры паролей помечают как скрытое, не записывается.
final class ClipboardMonitor: ObservableObject {
    @Published private(set) var groups: [ClipGroup] = []

    var onCopy: ((ClipGroup) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var changeCount: Int
    private var ownChangeCount: Int?
    private var timer: Timer?
    private var icons: [String: NSImage] = [:]

    private static let maxGroups = 12
    private static let maxItemsPerGroup = 25
    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    init() {
        changeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in self?.poll() }
    }

    func icon(for bundleID: String) -> NSImage {
        if let cached = icons[bundleID] { return cached }
        let image = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID)
            .map { NSWorkspace.shared.icon(forFile: $0.path) }
            ?? NSImage(systemSymbolName: "doc.on.clipboard", accessibilityDescription: nil)!
        icons[bundleID] = image
        return image
    }

    /// Положить элемент обратно в буфер обмена.
    func copy(_ item: ClipItem) {
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        ownChangeCount = pasteboard.changeCount
    }

    func remove(_ item: ClipItem) {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.8)) {
            for i in groups.indices { groups[i].items.removeAll { $0.id == item.id } }
            groups.removeAll { $0.items.isEmpty }
        }
    }

    func clear() {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.8)) { groups.removeAll() }
    }

    private func poll() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        guard changeCount != ownChangeCount else { return }

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skippedTypes) else { return }
        guard let raw = pasteboard.string(forType: .string) else { return }
        let text = String(raw.prefix(10_000))
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }

        let app = NSWorkspace.shared.frontmostApplication
        let bundleID = app?.bundleIdentifier ?? "unknown"
        let name = app?.localizedName ?? "Неизвестно"
        add(text: text, bundleID: bundleID, appName: name)
    }

    func add(text: String, bundleID: String, appName: String) {
        withAnimation(.spring(response: 0.45, dampingFraction: 0.78)) {
            // Один и тот же текст не повторяем: оставляем только самое свежее копирование.
            for i in groups.indices { groups[i].items.removeAll { $0.text == text } }
            var group = groups.first { $0.bundleID == bundleID }
                ?? ClipGroup(bundleID: bundleID, appName: appName, items: [])
            groups.removeAll { $0.bundleID == bundleID || $0.items.isEmpty }
            group.appName = appName
            group.items.insert(ClipItem(text: text, date: Date()), at: 0)
            group.items = Array(group.items.prefix(Self.maxItemsPerGroup))
            groups.insert(group, at: 0)
            groups = Array(groups.prefix(Self.maxGroups))
        }
        if let group = groups.first { onCopy?(group) }
    }
}
