import AppKit
import SwiftUI

struct ClipItem: Identifiable, Equatable, Codable {
    var id = UUID()
    var text: String
    var date: Date
    /// Своё название вместо начала текста (необязательно).
    var title: String?
}

/// Копирования из одного приложения собраны в одну группу.
struct ClipGroup: Identifiable, Equatable, Codable {
    var id: String { bundleID }
    var bundleID: String
    var appName: String
    var items: [ClipItem]

    var latest: Date { items.first?.date ?? .distantPast }
}

/// История буфера обмена. Хранится на диске заданное число дней (по умолчанию 7);
/// пароли и прочее, что менеджеры паролей помечают как скрытое, не записывается.
final class ClipboardMonitor: ObservableObject {
    @Published private(set) var groups: [ClipGroup] = []

    /// Сколько дней хранить историю; 0 — бесконечно.
    static let retentionOptions = [1, 7, 30, 0]
    var retentionDays: Int {
        get { UserDefaults.standard.object(forKey: "clipboard.retentionDays") as? Int ?? 7 }
        set {
            objectWillChange.send()
            UserDefaults.standard.set(newValue, forKey: "clipboard.retentionDays")
            prune()
        }
    }

    private let persistence: Bool
    private var saveWork: DispatchWorkItem?

    var onCopy: ((ClipGroup) -> Void)?
    /// Снимки экрана и скопированные картинки — отдельный раздел буфера.
    let shots: ScreenshotStore
    /// Записывать ли текст и картинки (переключатели в настройках).
    var recordsText = true
    var recordsImages = true

    private let pasteboard = NSPasteboard.general
    private var changeCount: Int
    private var ownChangeCount: Int?
    private var timer: Timer?
    private var icons: [String: NSImage] = [:]

    private static let maxGroups = 30
    private static let maxItemsPerGroup = 100
    private static let fileURL: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Notchly", isDirectory: true)
        try? FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        return base.appendingPathComponent("clipboard.json")
    }()
    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    init(persistent: Bool = true) {
        persistence = persistent
        shots = ScreenshotStore(persistent: persistent)
        changeCount = pasteboard.changeCount
        if persistent, let data = try? Data(contentsOf: Self.fileURL),
           let saved = try? JSONDecoder().decode([ClipGroup].self, from: data) {
            groups = saved
            prune()
        }
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in self?.poll() }
        // Раз в час убираем то, что старше срока хранения.
        Timer.scheduledTimer(withTimeInterval: 3600, repeats: true) { [weak self] _ in self?.prune() }
    }

    private func prune() {
        let days = retentionDays
        guard days > 0 else { return }
        let cutoff = Date().addingTimeInterval(-Double(days) * 86_400)
        var pruned = groups
        for i in pruned.indices { pruned[i].items.removeAll { $0.date < cutoff } }
        pruned.removeAll { $0.items.isEmpty }
        if pruned != groups {
            groups = pruned
            scheduleSave()
        }
    }

    private func scheduleSave() {
        guard persistence else { return }
        saveWork?.cancel()
        let snapshot = groups
        let work = DispatchWorkItem {
            guard let data = try? JSONEncoder().encode(snapshot) else { return }
            try? data.write(to: Self.fileURL, options: [.atomic, .completeFileProtection])
            // Только владельцу: в истории может быть что-то личное.
            try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: Self.fileURL.path)
        }
        saveWork = work
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 0.5, execute: work)
    }

    func icon(for bundleID: String) -> NSImage {
        if let cached = icons[bundleID] { return cached }
        let image = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID)
            .map { NSWorkspace.shared.icon(forFile: $0.path) }
            ?? NSImage(systemSymbolName: "doc.on.clipboard", accessibilityDescription: nil)!
        icons[bundleID] = image
        return image
    }

    /// Положить элемент обратно в буфер обмена.
    func copy(_ item: ClipItem) {
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        ownChangeCount = pasteboard.changeCount
    }

    /// Положить снимок в буфер обмена — сам себя в историю он не добавит.
    func copy(_ shot: Screenshot) {
        shots.write(shot, to: pasteboard)
        ownChangeCount = pasteboard.changeCount
    }

    /// Пустое название — вернуть показ начала текста.
    func rename(_ item: ClipItem, to title: String) {
        let clean = title.trimmingCharacters(in: .whitespacesAndNewlines)
        for g in groups.indices {
            if let i = groups[g].items.firstIndex(where: { $0.id == item.id }) {
                groups[g].items[i].title = clean.isEmpty ? nil : String(clean.prefix(80))
            }
        }
        scheduleSave()
    }

    func remove(_ item: ClipItem) {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.8)) {
            for i in groups.indices { groups[i].items.removeAll { $0.id == item.id } }
            groups.removeAll { $0.items.isEmpty }
        }
        scheduleSave()
    }

    func remove(group: ClipGroup) {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.85)) {
            groups.removeAll { $0.bundleID == group.bundleID }
        }
        scheduleSave()
    }

    func clear() {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.8)) { groups.removeAll() }
        scheduleSave()
    }

    private func poll() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        guard changeCount != ownChangeCount else { return }

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skippedTypes) else { return }
        guard let raw = pasteboard.string(forType: .string) else {
            // Картинка без текста: снимок экрана в буфер (⌃⇧⌘4) или «Скопировать изображение».
            let isImage = types.contains(NSPasteboard.PasteboardType.png.rawValue)
                || types.contains(NSPasteboard.PasteboardType.tiff.rawValue)
            let isFile = types.contains(NSPasteboard.PasteboardType.fileURL.rawValue)
            if recordsImages, isImage, !isFile { shots.add(pasteboard: pasteboard) }
            return
        }
        guard recordsText else { return }
        let text = String(raw.prefix(10_000))
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }

        let app = NSWorkspace.shared.frontmostApplication
        let bundleID = app?.bundleIdentifier ?? "unknown"
        let name = app?.localizedName ?? "Неизвестно"
        add(text: text, bundleID: bundleID, appName: name)
    }

    func add(text: String, bundleID: String, appName: String) {
        withAnimation(.spring(response: 0.45, dampingFraction: 0.78)) {
            // Один и тот же текст не повторяем: оставляем только самое свежее копирование (с его названием).
            let title = groups.lazy.flatMap(\.items).first { $0.text == text }?.title
            for i in groups.indices { groups[i].items.removeAll { $0.text == text } }
            var group = groups.first { $0.bundleID == bundleID }
                ?? ClipGroup(bundleID: bundleID, appName: appName, items: [])
            groups.removeAll { $0.bundleID == bundleID || $0.items.isEmpty }
            group.appName = appName
            group.items.insert(ClipItem(text: text, date: Date(), title: title), at: 0)
            group.items = Array(group.items.prefix(Self.maxItemsPerGroup))
            groups.insert(group, at: 0)
            groups = Array(groups.prefix(Self.maxGroups))
        }
        scheduleSave()
        if let group = groups.first { onCopy?(group) }
    }
}
