/// Английский перевод интерфейса. Ключ — русская строка из кода (с `%@` на месте подстановок).
/// Чего здесь нет, показывается по-русски — `scripts/check-l10n.py` находит такие строки.
enum English {
    static let table: [String: String] = [
        // Вкладки и разделы
        "Главная": "Home",
        "Музыка": "Music",
        "Таймер": "Timer",
        "Файлы": "Files",
        "Заметки и задачи": "Notes & Tasks",
        "Буфер обмена": "Clipboard",
        "Управление": "Controls",
        "Уведомления": "Notifications",
        "Заметки": "Notes",
        "Задачи": "Tasks",
        "История": "History",
        "Снимки": "Screenshots",
        "API-ключи": "API Keys",
        "Помидор": "Pomodoro",
        "Будильник": "Alarm",
        "Основные": "General",
        "Вкладки": "Tabs",
        "Остров": "Island",
        "О Notchly": "About Notchly",
        "Язык": "Language",
        "Настройки": "Settings",
        "Настройки…": "Settings…",
        "Настройки Notchly": "Notchly Settings",
        "Выйти из Notchly": "Quit Notchly",
        "Центр уведомлений": "Notification Center",

        // Главная
        "Задач на сегодня нет": "No tasks today",
        "Погода загружается…": "Loading weather…",
        "Нажмите, чтобы уточнить город по геолокации": "Click to use your precise location",
        "Открыть прогноз погоды на несколько дней": "Open the multi-day forecast",
        "Заряжается": "Charging",
        "Заряжается · %@": "Charging · %@",
        "только что": "just now",
        "%@ мин назад": "%@ min ago",
        "%@ ч назад": "%@ h ago",
        "Левый %@%% · правый %@%%": "Left %@%% · right %@%%",
        "Наушники": "Headphones",
        "Кейс": "Case",
        "Подключены": "Connected",
        "Подключено": "Connected",
        "Ясно": "Clear",
        "Почти ясно": "Mostly clear",
        "С прояснениями": "Partly cloudy",
        "Пасмурно": "Overcast",
        "Туман": "Fog",
        "Морось": "Drizzle",
        "Дождь": "Rain",
        "Снег": "Snow",
        "Ливень": "Showers",
        "Снегопад": "Snowfall",
        "Гроза": "Thunderstorm",
        "Облачно": "Cloudy",

        // Музыка
        "Сейчас ничего не играет": "Nothing is playing",
        "Включите музыку — обложка и управление появятся здесь": "Play some music — artwork and controls will appear here",
        "Повтор трека включён": "Repeat track is on",
        "Повторять этот трек": "Repeat this track",
        "Открыть %@": "Open %@",
        "Открыть %@ в браузере": "Open %@ in the browser",

        // Таймер
        "Фокус": "Focus",
        "Перерыв": "Break",
        "Длинный перерыв": "Long break",
        "Подходов сегодня: %@": "Rounds today: %@",
        "Идёт отсчёт": "Counting down",
        "Ближайший: %@": "Next: %@",
        "25 мин": "25 min",
        "Без задачи": "No task",
        "Фокус по технике «Помидор»": "Pomodoro focus",
        "25 мин работы · 5 мин перерыв · 15 мин после каждого 4-го": "25 min work · 5 min break · 15 min after every 4th",
        "Продолжить": "Resume",
        "Пауза": "Pause",
        "Закончить перерыв": "End break",
        "К перерыву": "Skip to break",
        "Остановить": "Stop",
        "Начать фокус": "Start focus",
        "К какой задаче привязать фокус": "Which task to focus on",
        "Подходы до длинного перерыва": "Rounds until the long break",
        "Осталось": "Left",
        "мин": "min",
        "сек": "sec",
        "Сбросить": "Reset",
        "Старт": "Start",
        "Добавить": "Add",
        "Будильников нет. Выберите время слева и нажмите «Добавить».": "No alarms. Pick a time on the left and click Add.",
        "Нажмите, чтобы ввести число": "Click to type a number",
        "Удалить будильник": "Delete alarm",
        "%@ ч": "%@ h",
        "%@ мин": "%@ min",
        "%@ с": "%@ s",
        "0 с": "0 s",

        // Карточки на острове
        "Таймер завершён": "Timer done",
        "Ещё раз": "Again",
        "Готово": "Done",
        "Будильник · %@": "Alarm · %@",
        "Пора!": "Time's up!",
        "+5 мин": "+5 min",
        "Стоп": "Stop",
        "Нажмите, чтобы увидеть заряд подробнее": "Click for battery details",
        "Длинный перерыв · 15 мин": "Long break · 15 min",
        "Перерыв · 5 мин": "Break · 5 min",
        "Перерыв окончен": "Break is over",
        "%@ · ждут уведомления: %@": "%@ · notifications waiting: %@",
        "Готовы к следующему подходу?": "Ready for the next round?",
        "Пропустить": "Skip",
        "Войти": "Join",
        "Открыть": "Open",
        "Напомнить через 5 минут": "Remind me in 5 minutes",
        "сейчас": "now",
        "Зарядка": "Charging",
        "Через %@ мин · %@": "In %@ min · %@",
        "Начинается сейчас · %@": "Starting now · %@",
        "Началось в %@": "Started at %@",
        "Событие": "Event",

        // Заметки и задачи
        "Начните печатать…": "Start typing…",
        "Название": "Name",
        "Переименовать": "Rename",
        "Переименовать…": "Rename…",
        "Удалить": "Delete",
        "Новая заметка": "New note",
        "Сегодня": "Today",
        "Завтра": "Tomorrow",
        "сегодня": "today",
        "завтра": "tomorrow",
        " · задач: %@": " · tasks: %@",
        "Убрать выполненные": "Remove completed",
        "На %@ задач нет": "No tasks for %@",
        "Новая задача": "New task",
        "Задача на %@": "Task for %@",
        "Нажмите, чтобы исправить": "Click to edit",
        "Фокус 25 минут над этой задачей": "Focus on this task for 25 minutes",
        "Добавить описание": "Add a description",
        "Открыть описание": "Open the description",
        "Удалить задачу": "Delete task",
        "Свернуть описание": "Collapse the description",
        "Ссылка": "Link",
        "Описание: что сделать, ссылка на урок, заметки…": "Description: what to do, a lesson link, notes…",
        "Удалить ключ API": "Remove API key",
        "Думаю…": "Thinking…",
        "Добавлено задач: %@": "Tasks added: %@",
        "Расскажите о планах: «сегодня в 5 спортзал, в 10 созвон» — разложу по задачам.":
            "Tell me your plans: “gym at 5 today, call at 10” — I'll turn them into tasks.",
        "Спросить Gemini": "Ask Gemini",
        "Вставьте ключ API из Google AI Studio. Он хранится в Связке ключей.":
            "Paste an API key from Google AI Studio. It is stored in the Keychain.",
        "Ключ API": "API key",
        "Сохранить": "Save",
        "Получить ключ →": "Get a key →",
        "Мелкий": "Small",
        "Обычный": "Regular",
        "Крупный": "Large",
        "Заголовок": "Heading",
        "Жирный": "Bold",
        "Курсив": "Italic",
        "Зачёркнутый": "Strikethrough",
        "Размер шрифта": "Font size",

        // Gemini
        "Не удалось сохранить ключ в Связке ключей": "Couldn't save the key to the Keychain",
        "Gemini недоступен": "Gemini is unavailable",
        "Пустой ответ от Gemini": "Empty response from Gemini",
        "Ключ API не подошёл": "The API key was rejected",
        "Лимит бесплатных запросов исчерпан — попробуйте позже": "Free request limit reached — try again later",
        "Серверы Gemini сейчас перегружены — попробуйте через минуту": "Gemini servers are overloaded — try again in a minute",
        "Google сменил модели Gemini — обновите приложение": "Google changed the Gemini models — update the app",
        "Ошибка Gemini (%@)": "Gemini error (%@)",

        // Буфер обмена
        "Скопируйте что-нибудь — оно появится здесь": "Copy something — it will show up here",
        "Удалить всё из %@": "Delete everything from %@",
        "Название — например, «Адрес доставки»": "Name — e.g. “Delivery address”",
        "Скопировано": "Copied",
        "Скопировать": "Copy",
        "Нажмите, чтобы скопировать": "Click to copy",
        "Неизвестно": "Unknown",
        "Снимки удаляются сами через этот срок. Изменить — в настройках Notchly.":
            "Screenshots are deleted automatically after this period. Change it in Notchly Settings.",
        "История буфера выключена в настройках": "Clipboard history is turned off in Settings",
        "Точно очистить?": "Clear everything?",
        "Очистить": "Clear",
        "Снимки выключены в настройках": "Screenshots are turned off in Settings",
        "Снимок в буфер (⌃⇧⌘4) или скопированная картинка появится здесь на %@ %@":
            "A screenshot to the clipboard (⌃⇧⌘4) or a copied image will stay here for %@ %@",
        "Брать и снимки с рабочего стола": "Also keep Desktop screenshots",
        "macOS один раз спросит доступ к папке со снимками": "macOS will ask once for access to the screenshots folder",
        "Сохранить копию…": "Save a Copy…",
        "Нажмите, чтобы дать название": "Click to name it",
        "%@ · %@. Нажмите, чтобы переименовать": "%@ · %@. Click to rename",
        "Нажмите — скопировать, перетащите — вставить в другое приложение": "Click to copy, drag into another app to paste",
        "Снимок %@": "Screenshot %@",
        "API-ключи защищены": "API keys are locked",
        "Нажмите и подтвердите Touch ID или паролем Mac": "Click and confirm with Touch ID or your Mac password",
        "Ключей пока нет": "No keys yet",
        "Разблокировано": "Unlocked",
        "Заблокировать": "Lock",
        "Ключ": "Key",
        "Ключ %@": "Key %@",
        "Вставить из буфера обмена": "Paste from the clipboard",
        "Скопировать ключ": "Copy key",
        "На этом Mac недоступны Touch ID и пароль": "Touch ID and password aren't available on this Mac",
        "открыть API-ключи": "unlock API keys",
        "Не удалось подтвердить личность": "Couldn't verify your identity",

        // Файлы
        "Файлы · %@": "Files · %@",
        "Перетащите файлы сюда, чтобы подержать их под рукой": "Drop files here to keep them at hand",
        "Убрать из файлов": "Remove from Files",
        "Показать в Finder": "Show in Finder",
        "Отправить по AirDrop": "Send with AirDrop",
        "Скопировать путь": "Copy Path",

        // Управление
        "Громкость": "Volume",
        "Яркость": "Brightness",
        "Устройство вывода не поддерживает регулировку": "The output device doesn't support volume control",
        "Недоступно для этого дисплея": "Not available for this display",
        "Приложения": "Apps",
        "Настройки Notchly: вкладки, функции, уведомления, буфер обмена": "Notchly settings: tabs, features, notifications, clipboard",
        "Разрешите запись системного аудио, чтобы менять громкость приложений": "Allow system audio recording to change per-app volume",
        "Открыть настройки": "Open Settings",
        "Нужна macOS 14.2 или новее": "Requires macOS 14.2 or later",

        // Уведомления и почта
        "Очистить всё": "Clear All",
        "Новых уведомлений нет": "No new notifications",
        "Не подключено": "Not connected",
        "Непрочитанных писем нет": "No unread mail",
        "Открыть Gmail": "Open Gmail",
        "Обновить": "Refresh",
        "Отключить": "Disconnect",
        "Удалить все уведомления %@": "Delete all notifications from %@",
        "Telegram, WhatsApp и другие приложения": "Telegram, WhatsApp and other apps",
        "Нужен «Полный доступ к диску». Уже выдан? Удалите Notchly из списка и добавьте снова":
            "Needs Full Disk Access. Already granted? Remove Notchly from the list and add it again",
        "Открыть письмо в Gmail": "Open the email in Gmail",
        "Удалить уведомление": "Delete notification",
        "Пароль приложения": "App password",
        "Подключить": "Connect",
        "Нужен пароль приложения Google, не основной пароль.": "Use a Google app password, not your main password.",
        "Создать →": "Create →",
        "(без темы)": "(no subject)",
        "Введите пароль приложения ещё раз — старая сборка сохранила его недоступным":
            "Enter the app password again — an older build stored it in an unreadable way",
        "Не удалось обновить почту": "Couldn't refresh mail",
        "Gmail не ответил вовремя": "Gmail didn't respond in time",
        "Gmail не принял адрес или пароль приложения": "Gmail rejected the address or app password",
        "Gmail не отвечает": "Gmail isn't responding",
        "Соединение с Gmail закрыто": "The connection to Gmail was closed",
        "Не удалось прочитать базу уведомлений: %@": "Couldn't read the notification database: %@",

        // Настройки
        "Запускать при входе в систему": "Open at login",
        "Значок в строке меню": "Menu bar icon",
        "Без значка настройки открываются из вкладки «Управление» или повторным запуском Notchly.":
            "Without the icon, open Settings from the Controls tab or by launching Notchly again.",
        "Открывать на вкладке": "Open on tab",
        "Последняя открытая": "Last opened",
        "Закрывать, когда курсор ушёл, через": "Close after the pointer leaves",
        "Задержка": "Delay",
        "Раскрытый остров": "Expanded island",
        "Клик мимо острова закрывает его сразу.": "Clicking outside the island closes it right away.",
        "Слева от выреза": "Left of the notch",
        "Справа от выреза": "Right of the notch",
        "Пусто": "Empty",
        "Колокольчик уведомлений всегда стоит справа, последним. Главная всегда видна.":
            "The notification bell always stays last on the right. Home is always visible.",
        "Как было": "Reset",
        "Левее / выше": "Move left / up",
        "Правее / ниже": "Move right / down",
        "Перенести направо от выреза": "Move to the right of the notch",
        "Перенести налево от выреза": "Move to the left of the notch",
        "Главная всегда видна": "Home is always visible",
        "Показывать вкладку": "Show tab",
        "Свёрнутый остров": "Collapsed island",
        "Музыка: обложка и эквалайзер по бокам выреза": "Music: artwork and equalizer beside the notch",
        "Шторка с названием нового трека": "Show the new track's title",
        "Громкость и яркость вместо системного индикатора": "Volume and brightness instead of the system HUD",
        "«Скопировано» при копировании": "“Copied” when you copy",
        "Карточки": "Cards",
        "Подключили зарядку": "Charger connected",
        "Подключили наушники (заряд AirPods)": "Headphones connected (AirPods battery)",
        "Уведомления приложений": "App notifications",
        "Новые письма Gmail": "New Gmail messages",
        "Напоминания о задачах и встречах": "Task and meeting reminders",
        "Показывать на острове": "Show on the island",
        "Всё пришедшее остаётся в центре уведомлений (колокольчик) — выключается только всплывающая карточка. Во время «Помидора» уведомления копятся молча.":
            "Everything still lands in the notification center (the bell) — only the pop-up card is turned off. During Pomodoro, notifications wait quietly.",
        "Тихий сигнал: напоминания, таймер, будильник": "Soft chime: reminders, timer, alarm",
        "Прослушать": "Play",
        "Текст": "Text",
        "Запоминать скопированный текст": "Remember copied text",
        "Хранить историю": "Keep history",
        "Очистить историю…": "Clear History…",
        "Очистить всю историю буфера обмена?": "Clear the entire clipboard history?",
        "Сохранять снимки экрана и скопированные картинки": "Keep screenshots and copied images",
        "Брать и снимки, сохранённые на рабочий стол": "Also keep screenshots saved to the Desktop",
        "Хранить снимки": "Keep screenshots",
        "Занято": "Used",
        "%@ шт. · %@": "%@ items · %@",
        "Удалить все снимки…": "Delete All Screenshots…",
        "Удалить все сохранённые снимки?": "Delete all saved screenshots?",
        "Снимок весит 1–8 МБ, поэтому они хранятся недолго: не больше %@ штук, старые удаляются сами. Снимки с рабочего стола копируются — оригиналы остаются на месте. Для них macOS один раз спросит доступ к папке.":
            "A screenshot takes 1–8 MB, so they are kept briefly: at most %@, older ones are deleted automatically. Desktop screenshots are copied — the originals stay where they are. macOS asks once for folder access.",
        "Бесконечно": "Forever",
        "Версия %@": "Version %@",
        "Остров в вырезе экрана: музыка, задачи, таймеры, напоминания и уведомления.\nВсе данные хранятся только на этом Mac.":
            "An island in your screen's notch: music, tasks, timers, reminders and notifications.\nAll data stays on this Mac.",
        "Язык интерфейса меняется сразу, без перезапуска.": "The interface language changes right away, no restart needed.",
    ]
}
